// Content data for the design concept build. Mirrors src/data/*.ts.
// Regenerate pages with: node scripts/build-concept.mjs

const programs = [
  {
    slug: "meditate-with-a-monk",
    title: "Meditate with a Monk",
    kicker: "Begin here",
    summary: "A calm, guided evening with a resident monk. Simple breathing, loving-kindness, and time for questions. Built for people who have never meditated, and for anyone who wants to sit with a teacher.",
    when: "Public sessions across the DMV, plus Utah and California dates",
    where: "Community venues and the Rockville monastery",
    image: "/images/washington.webp",
    alt: "Visitors sitting with a monk during a Meditate with a Monk session",
    cta: "Find a session",
    href: "https://www.eventbrite.com/e/meditate-with-a-monk-registration-1992957208660?aff=oddtdtcreator",
    group: "first",
    body: [
      "Modern life pulls the mind in a hundred directions. This session is a reset: sit with a monk, follow a simple instruction, and leave with a practice you can actually use.",
      "The evening is a mindfulness experience led by Buddhist monks, designed for non-Buddhists. The focus is well-being, not religious conversion.",
    ],
    includes: ["Guided sitting meditation", "Short, practical instruction", "Time for questions", "Chairs provided; cushions welcome"],
    audience: "Anyone. No Buddhist background needed.",
  },
  {
    slug: "sunday-evening",
    title: "Sunday evening meditation",
    kicker: "Weekly, in person",
    summary: "Guided meditation followed by a Dhamma talk or Q&A. A steady weekly hour to come back to the breath, in the shrine room at the center.",
    when: "Sundays, 5:00 – 7:00 pm",
    where: "Buddha Meditation Center, Rockville, MD",
    image: "/images/shrine-room.jpg",
    alt: "People sitting in meditation in the Rockville shrine room",
    cta: "Reserve a seat",
    href: "https://www.eventbrite.com/e/sunday-meditation-registration-1225425684209",
    group: "regular",
    body: [
      "Sunday evening is the center’s home practice. Arrive a little early, take a seat, and let the room settle around you.",
      "The sitting is followed by a short talk or open questions with the resident monks.",
    ],
    includes: ["Guided sitting", "Walking practice as offered", "Talk or Q&A", "Community after the sit"],
    audience: "Anyone seeking a regular in-person practice.",
  },
  {
    slug: "online",
    title: "Weekly online meditation",
    kicker: "Digital monastery",
    summary: "Join from anywhere. A weekly Zoom sitting with the same monks who teach in Rockville, made for people who cannot travel, or who want a midweek anchor.",
    when: "Thursdays, 8:00 – 9:00 pm ET",
    where: "Zoom",
    image: "/images/monk-portrait.jpeg",
    alt: "A monk teaching, the same teachers who sit on Zoom",
    cta: "Join on Zoom",
    href: "https://mahamevnawa.zoom.us/j/81813080318?pwd=Zi9zIdEpWYbIuYkjuZSaAgL830ZcOS.1",
    group: "online",
    body: [
      "The digital monastery is simple: a Zoom room, a monk, and an hour of practice. Camera on or off. Sit in a chair at home.",
      "If you are far from DC, this is your weekly hall.",
    ],
    includes: ["Guided mindfulness", "Interactive discussion", "Beginner-friendly instruction"],
    audience: "Anyone, worldwide.",
  },
  {
    slug: "day-long",
    title: "Day-long meditation retreat",
    kicker: "Go deeper",
    summary: "A full Saturday of sitting, walking, and loving-kindness, with meals in noble quiet. For people who want more than an evening hour.",
    when: "1st & 3rd Saturday, 9:00 am – 4:00 pm",
    where: "Buddha Meditation Center, Rockville, MD",
    image: "/images/outdoor-group.webp",
    alt: "A group sitting outdoors during a day-long retreat",
    cta: "See upcoming dates",
    href: "https://www.eventbrite.com/e/day-long-meditation-retreat-tickets-1533409401799",
    group: "regular",
    body: [
      "The day unfolds slowly: sitting, walking, a meal, more sitting. Monks guide the rhythm so you do not have to invent a schedule.",
      "Monthly donors may attend day-long retreats as part of their pledge.",
    ],
    includes: ["Sitting and walking meditation", "Loving-kindness practice", "Vegetarian meal", "Guidance from resident monks"],
    audience: "Beginners who can sit a full day, and experienced meditators.",
  },
  {
    slug: "two-day",
    title: "Two-day retreat",
    kicker: "Overnight",
    summary: "One night away from ordinary life at Wellspring Retreat Center in Germantown. Guided and silent sits, vegetarian meals, and simple shared lodging.",
    when: "Scheduled weekends",
    where: "Wellspring Retreat Center, Germantown, MD",
    image: "/images/hero-walking.jpg",
    alt: "Walking meditation on a wooded path",
    cta: "Ask about the next dates",
    href: "contact.html",
    group: "regular",
    body: [
      "Two days is long enough for the mind to stop rehearsing the week. The retreat includes sitting, walking, mindful meals, and time with the monks.",
      "Lodging is simple: two beds to a room, with separate cabin areas for men, women, and high school students. This is a fee-based program. Monthly donors receive 40% off.",
    ],
    includes: ["Guided and silent sits", "Vegetarian meals", "Shared lodging", "One-on-one guidance as offered"],
    audience: "Committed beginners through experienced meditators.",
  },
  {
    slug: "monthly",
    title: "Monthly mindfulness at Sandy Spring",
    kicker: "Museum evening",
    summary: "A public mindfulness evening at Sandy Spring Museum. Present-moment awareness, loving-kindness, and emotional ease, offered in a civic space rather than a shrine room.",
    when: "First Tuesday, 6:30 – 8:00 pm",
    where: "Sandy Spring Museum",
    image: "/images/sandy-spring-hall.jpg",
    alt: "A large hall of people meditating at Sandy Spring Museum",
    cta: "Learn more",
    href: "contact.html",
    group: "first",
    body: ["Some people are not ready to walk into a monastery. Sandy Spring is for them: a museum hall, chairs in rows, and a monk offering tools you can take home."],
    includes: ["Guided mindfulness", "Loving-kindness", "A civic, public setting"],
    audience: "People looking for practical stress relief, including non-Buddhists.",
  },
  {
    slug: "children",
    title: "Mindfulness for children",
    kicker: "Ages 6–15",
    summary: "Sunday morning for young people: focus, kindness, and emotional balance, taught in an age-appropriate way by the monks.",
    when: "Sundays, 9:00 – 11:00 am",
    where: "Buddha Meditation Center, Rockville, MD",
    image: "/images/children.jpeg",
    alt: "Children smiling during a mindfulness program",
    cta: "Sign a child up",
    href: "contact.html",
    group: "regular",
    body: ["Children learn to notice the breath, name a feeling, and treat each other with care. The tone is warm, not stern."],
    includes: ["Age-appropriate sitting", "Kindness practices", "Group activities"],
    audience: "Children ages 6–15, with a parent nearby as requested.",
  },
  {
    slug: "sutta-class",
    title: "Mindfulness through Buddhist Sutta class",
    kicker: "For those who want to go further",
    summary: "A weekly online reading of the Buddha’s discourses with Theravada monks. This is the deeper path: not required, available when someone asks for it.",
    when: "Wednesdays, 8:00 – 9:00 pm ET",
    where: "Zoom",
    image: "/images/monk-portrait.jpeg",
    alt: "A resident monk of Buddha Meditation Center",
    cta: "Join the class",
    href: "https://mahamevnawa.zoom.us/j/87095076489?pwd=VmUwTEUwTHdBd0dpYm1PZzlOTnQ0QT09",
    group: "deeper",
    body: [
      "Suttas are the Buddha’s discourses, preserved in the Pali Canon. Each week the monks read, explain, and leave room for questions.",
      "This sits at the far end of the path on purpose. First we offer calm. Then, for those who want it, we offer the teaching in full.",
    ],
    includes: ["Live reading", "Monk-led explanation", "Open discussion", "Recordings via the WhatsApp community"],
    audience: "Anyone curious about the original teachings. No prior study needed.",
  },
  {
    slug: "sinhala",
    title: "Sinhala language programs",
    kicker: "සිංහල",
    summary: "Monthly sil meditation and weekly Sutta Nipata study in Sinhala, for the Sri Lankan community and anyone who practices in Sinhala.",
    when: "Monthly Uposatha days, plus Thursday 7:00 – 8:00 pm",
    where: "Center and Google Meet",
    image: "/images/shrine-room.jpg",
    alt: "The shrine room during a community gathering",
    cta: "Join in Sinhala",
    href: "contact.html",
    group: "deeper",
    body: ["මාසික සීල භාවනා වැඩසටහන සහ සතිපතා සුත්ත නිපාතය දේශනාව. Sinhala speakers can keep a complete practice in their own language: precepts, dana, and sutta study."],
    includes: ["Monthly sil day", "Thursday Sutta Nipata", "Google Meet option"],
    audience: "Sinhala speakers and families.",
  },
  {
    slug: "workplace",
    title: "Meditation at work",
    kicker: "Invited programs",
    summary: "Bring a monk-led session to an office, school, or nonprofit. Short introductions or two-hour workshops, offered by donation.",
    when: "By invitation",
    where: "Your workplace or campus",
    image: "/images/community-group.jpg",
    alt: "Community members gathered with monks",
    cta: "Invite a session",
    href: "contact.html",
    group: "first",
    body: ["Sessions are secular in tone, rooted in authentic Buddhist mindfulness, and shaped for the room in front of us. There is no fixed fee."],
    includes: ["Guided mindfulness", "Tools for stress and focus", "Optional short Dhamma remarks"],
    audience: "Teams, schools, agencies, and community groups.",
  },
];

const groups = [
  { id: "first", title: "A first visit", copy: "Open doors. No background required." },
  { id: "regular", title: "A regular practice", copy: "Weekly sits and retreats near DC." },
  { id: "online", title: "The digital monastery", copy: "Join from anywhere." },
  { id: "deeper", title: "If you want to go further", copy: "Study, when you ask for it." },
];

const events = [
  ["Sunday evening meditation", "Every Sunday, 5:00 – 7:00 pm", "https://www.eventbrite.com/e/sunday-meditation-registration-1225425684209", "/images/shrine-room.jpg", "Sunday sitting in the Rockville shrine room", "Buddha Meditation Center, Rockville"],
  ["Day-long meditation retreat", "1st & 3rd Saturday, 9:00 am – 4:00 pm", "https://www.eventbrite.com/e/day-long-meditation-retreat-tickets-1533409401799", "/images/outdoor-group.webp", "People sitting during a day-long retreat", "Rockville monastery"],
  ["Meditate with a Monk", "Public sessions across the DMV", "https://www.eventbrite.com/e/meditate-with-a-monk-registration-1992957208660?aff=oddtdtcreator", "/images/washington.webp", "A monk teaching a public session", "Community venues"],
  ["Meditate with a Monk · Vienna", "Scheduled community venues", "https://www.eventbrite.com/e/meditate-with-a-monk-in-vienna-tickets-1538904537899", "/images/monk-portrait.jpeg", "A monk teaching in a civic hall", "Vienna, Virginia"],
];

const quote = "I came tired and left lighter. The monk did not push a belief. He taught me how to sit with my own mind.";
const donate = "https://www.zeffy.com/en-US/ticketing/online-meditation";
const map = "https://maps.google.com/maps?q=Buddha%20Meditation%20Center%2C%205004%20Stone%20Rd%2C%20Rockville%2C%20MD&t=m&z=16&output=embed";

const nav = [
  ["programs.html", "Programs"],
  ["about.html", "About"],
  ["visit.html", "Visit"],
  ["donate.html", "Donate"],
];

export { programs, groups, events, quote, donate, map, nav };
